[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && ./target/release/backend"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["openssl", "pkg-config"]

[phases.build]
cmds = ["cd backend && cargo build --release"] 